## 넘파이 ndarray 개요

In [3]:
import numpy as np

In [4]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],[2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


1. np.array()  
  - ndarray로 변환을 원하는 객체를 인자로 입력하면 ndarray를 반환한다.  
  - 넘파이의 기반 데이터 타입은 ndarray이다.  
  - ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산을 수행할 수 있다.  
  - 생성된 ndarray 배열의 shape 변수는 ndarray의 크기, 즉 행과 열의 수를 튜플 형태로 가지고 있으며 이를 통해 ndarray 배열의 차원까지 알 수 있다. 
  - array() 함수의 인자로는 파이썬의 리스트 객체가 주로 사용된다. 리스트 []는 1차원이고, 리스트의 리스트 [[]]는 2차원과 같은 형태로 배열의 차원과 크기를 쉽게 표현할 수 있기 때문이다.
  
  
2. ndarray.shape  
  - ndarray의 차원과 크기를 튜플 형태로 나타낸다.  
  ex. [1,2,3]인 array1의 shape : (3,) -> 1차원 array로 3개의 데이터를 가지고 있다.  
  ex. [[1,2,3],[2,3,4]]인 array2의 shape : (2,3) -> 2차원 array로 2개의 행과 3개의 열로 구성되어 6개의 데이터를 가지고 있다.  
  ex. [[1,2,3]]]인 array3의 shape : (1,3) -> 2차원 array로 1개의 행과 3개의 열로 구성되어 3개의 데이터를 가지고 있다.  


3. ndarray.ndim  
  - array의 차원 확인

In [5]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


- format 함수  
(참고 : https://blockdmask.tistory.com/424)  

### ndarray의 데이터 타입

1. ndarray 내의 데이터값은 숫자 값, 문자열 값, 불 값 등이 모두 가능하다.  
2. 숫자형의 경우 int형(8bit, 16bit, 32bit), unsigned int형(8bit, 16bit, 32bit), float형(16bit, 32bit, 64bit, 128bit), 이보다 더 큰 숫자 값이나 정밀도를 위해 complex 타입도 제공한다.  
3. ndarray내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능하다.
  - ndarray 내의 데이터 타입은 dtype 속성으로 확인가능하다.

In [6]:
list1 = [1,2,3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


4. 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용한다.

In [9]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2,array2.dtype) # 모두 문자열 값으로 변환

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype) # float64형으로 반환

['1' '2' 'test'] <U11
[1. 2. 3.] float64


5. ndarray 내 데이터 값의 타입 변경도 astype() 메서드를 이용해 할 수 있다.  
    - astype()에 인자로 원하는 타입을 문자열로 지정하면 된다.  
    - 이렇게 데이터 타입을 변경하는 경우는 대용량 데이터의 ndarrary를 만들 때 많은 메모리가 사용되는데, 메모리를 더 절약해서 할 때 보통 이용된다.  

In [10]:
# int32형 -> float64 -> int32
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

# float -> int
array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2,array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

1. arange()  
  - array를 range()로 표현  
  - 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환
  - default 함수 인자는 stop 값이며 0부터 stop값-1까지의 연속 숫자 값으로 구성된 1차원 ndarray를 만들어 준다.
  - start 값도 부여해 0이 아닌 다른 값부터 시작한 연속 값을 부여할 수도 있다.

In [13]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


2. zeros()
  - 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환  


3. ones()
  - 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환  


- 함수 인자로 dtype을 정해주지 않으면 default로 float64형의 데이터로 ndarray를 채운다.

In [14]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape) # default : float64

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape()

1. reshape()  
  - ndarray를 특정 차원 및 크기로 변환  
  - 변환을 원하는 크기를 함수 인자로 부여 

In [16]:
# 0~9까지의 1차원 ndarray를 2*5, 5*2 형태로 2차원 ndarray로 변환
array1 = np.arange(10)
print('array1:\n',array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [17]:
array1.reshape(4,3) # 오류 발생
                    # 지정된 사이즈로 변경이 불가능하면 오류 발생

ValueError: cannot reshape array of size 10 into shape (4,3)

- <u>-1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환</u>

In [19]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [22]:
print(array2)
print(array3)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


(1) array2  
  - array1은 1차원 ndarray로 0~9까지의 데이터를 가지고 있다.  
  - array2는 array1.reshape(-1,5)로, row 인자가 -1, column 인자가 5이다.  
  => array1과 호환될 수 있는 2차원 ndarray로 변환하되, **<u>고정된 5개의 칼럼에 맞는 로우를 자동으로 새롭게 생성해 변환</u>**하라는 의미  
  => 10개의 1차원 데이터와 호환될 수 있는 고정된 5개 칼럼에 맞는 로우 개수는 2이므로 2 * 5의 2차원 ndarray로 변환


(2) array3
  - 10개의 1차원 데이터와 호환될 수 있는 고정된 5개의 로우에 맞는 칼럼은 2이므로 5 * 2의 2차원 ndarray로 변환

In [23]:
# 호환될 수 없는 경우 있음(오류 발생)
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

**reshape(-1,1)**
  - -1 인자는 reshape(-1,1)와 같은 형태로 자주 사용된다.  
  - reshape(-1,1)은 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장한다.  

In [25]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist()) # tolist() 메서드를 이용해 리스트 자료형으로 변환할 수 있다

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:\n', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape:
 (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [26]:
array1.reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

## 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

**1. 특정한 데이터만 추출** : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환한다.  
**2. 슬라이싱(Slicing)** : 슬라이싱은 연속된 인덱스간의 ndarray를 추출하는 방식이다. ':' 기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 <u>시작 인덱스에서 종료 인덱스-1 위치에 있는 데이터의 ndarray</u>를 반환한다.  
**3. 팬시 인덱싱(Fancy Indexing)** : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환한다.  
**4. 불린 인덱싱(Boolean Indexing)** : 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환한다.  

### 단일 값 추출


In [28]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1,stop=10)
print('array1:',array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:',value)
print(type(value)) # array1[2]의 타입은 ndarray 타입이 아니고 ndarray 내의 데이터값을 의미

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [30]:
print('맨 뒤의 값:',array1[-1], ' 맨 뒤에서 두 번째 값:',array1[-2])

맨 뒤의 값: 9  맨 뒤에서 두 번째 값: 8


In [31]:
# 단일 인덱스를 이용해 ndarray 내의 데이터 값 수정
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [32]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3) # 3*3 ndarray로 변환
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0])
print('(row=0,col=1) index 가리키는 값:', array2d[0,1])
print('(row=1,col=0) index 가리키는 값:', array2d[1,0])
print('(row=2,col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


- **axis 0 : 로우 방향의 축, axis 1 : 칼럼 방향의 축**  
- 정확히 말하면, 앞 설명에서 지칭한 로우와 칼럼은 넘파이 ndarray에서는 사용되지 않는 방식이다.  
  => [row=0, col=1] 인덱싱은 [axis 0=0, axis1=1]이 정확한 표현이다.  
- 축 기반의 연산에서 axis가 생략되면 axis 0을 의미한다.

### 슬라이싱

In [3]:
import numpy as np

array1 = np.arange(start=1,stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


1. ':' 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주한다.  
2. ':' 기호 뒤에 종료 인덱스를 생랴갛면 자동으로 맨 마지막 인덱스로 간주한다.  
3. ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주한다.  

In [4]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [6]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)
print('array2d[0:2,0:2]\n',array2d[0:2,0:2])
print('array2d[1:3,0:3]\n',array2d[1:3,0:3])
print('array2d[1:3,:]\n',array2d[1:3,:])
print('array2d[:,:]\n',array2d[1:3])
print('array2d[:2,1:]\n',array2d[:2,1:])
print('array2d[:2,0]\n',array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]


In [7]:
print(array2d[0]) # 첫 번째 로우
print(array2d[1]) # 두 번쨰 로우
print('array2d[0] shape:',array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


### 팬시 인덱싱

- 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식이다.  

In [11]:
array1d = np.arange(start=1, stop=10) # array([1, 2, 3, 4, 5, 6, 7, 8, 9])
array2d = array1d.reshape(3,3) # array([[1, 2, 3],
                               #        [4, 5, 6],
                               #        [7, 8, 9]])

array3 = array2d[[0,1],2]  
print('array2d[[0,1],2]=>',array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2]=>',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]]=>',array5.tolist()) # array([[1, 2, 3],
                                         #         [4, 5, 6]])

array2d[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


- array3는 로우 축에 팬시 인덱싱인 [0,1]을 칼럼 축에는 단일 값 인덱싱 2를 적용한다.  
- array5는 ((0,:),(1:)) 인덱싱이 적용돼 [[1,2,3],[4,5,6]]을 반환한다.

### 불린 인덱싱  
- 조건 필터링과 검색을 동시에 할 수 있기 땜누에 매우 자주 사용되는 인덱싱 방식이다.  
- ndarray의 인덱스를 지정하는 [] 내에 조건문을 그대로 기재하면 된다.  

In [20]:
array1d = np.arange(start=1, stop=10)

# [] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d>5]
print('array1d > 5 불린 인덱싱 결과 값 :',array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [21]:
array1d>5 # 5보다 큰 데이터가 있는 위치는 true를 반환

array([False, False, False, False, False,  True,  True,  True,  True])

In [22]:
boolean_indexes = np.array([False,False,False,False,False,True,True,True,True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :',array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [23]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


불린 인덱싱이 동작하는 단계  
1. Step 1 : array1d > 5와 같이 ndarray의 필터링 조건을 []안에 기재  
2. Step 2 : False 값은 무시하고 True 값에 해당하는 인덱스값만 저장  
3. Step 3 : 저장된 인덱스 데이터 세트로 ndarray 조회

## 행렬의 정렬 - sort()와 argsort()

- 넘파이에서 행렬을 정렬하는 대표적인 방법 : np.sort(), ndarray.sort()  
- 정렬된 행렬의 인덱스를 반환 : argsort()

### 행렬 정렬

- np.sort() : 원행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환  
- ndarray.sort() : 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None  

In [25]:
org_array = np.array([3,1,9,5])
print('원본 행렬:',org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:',sort_array1)
print('np.sort() 호출 후 원본 행렬:',org_array)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:',sort_array2)
print('org_array.sort() 호출 후 원본 행렬:',org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [26]:
# 기본적으로 오름차순으로 행렬 내 원소를 정렬

# 내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [27]:
# 행렬이 2차원 이상일 경우
array2d = np.array([[8,12],
                   [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n',sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


### 정렬된 행렬의 인덱스를 반환하기

- np.argsort()는 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환한다.

In [28]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [30]:
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:',sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


## 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

### 행렬 내적(행렬 곱)

In [32]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])

dot_product = np.dot(A,B)
print('행렬 내적 결과:\n',dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


### 전치 행렬  
- 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬

In [33]:
A = np.array([[1,2],
             [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n',transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
